version: "3"

services:
  psql:
    image: postgres:13.3
    container_name: psql
    environment: &dbConfig
      POSTGRES_DB: database
      POSTGRES_USER: database_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_PORT: "5432"
    ports:
      - "5432:5432"
    volumes:
      - "./psql-data:/var/lib/postgresql/data"
  # redis:
  #   image: redis:6.2.5
  #   container_name: redis
  #   command: ['--appendonly yes']
  #   volumes:
  #     - ./redis-data:/data
  backend:
    build:
      context: "./backend"
      dockerfile: dev.Dockerfile
    container_name: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./backend/.env
    environment:
      POSTGRES_HOST: psql
      <<: *dbConfig
    ports:
      - "8000:8000"
    depends_on:
      - psql
    restart: on-failure
    volumes:
      - ./backend/backend:/app
  frontend:
    build:
      context: "./frontend"
      dockerfile: dev.Dockerfile
    container_name: frontend
    command: ["npm", "run", "start"]
    env_file: ./frontend/.env.development
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
      - "35729:35729"
    restart: on-failure
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/.env.development:/app/.env.development
